theme-options: &theme-options
  options:
    - value: "andromeeda"
      label: "Andromeeda"
    - value: "aurora-x"
      label: "Aurora X"
    - value: "ayu-dark"
      label: "Ayu Dark"
    - value: "catppuccin-frappe"
      label: "Catppuccin Frappé"
    - value: "catppuccin-latte"
      label: "Catppuccin Latte"
    - value: "catppuccin-macchiato"
      label: "Catppuccin Macchiato"
    - value: "catppuccin-mocha"
      label: "Catppuccin Mocha"
    - value: "dark-plus"
      label: "Dark Plus"
    - value: "dracula"
      label: "Dracula Theme"
    - value: "dracula-soft"
      label: "Dracula Theme Soft"
    - value: "everforest-dark"
      label: "Everforest Dark"
    - value: "everforest-light"
      label: "Everforest Light"
    - value: "github-dark"
      label: "GitHub Dark"
    - value: "github-dark-default"
      label: "GitHub Dark Default"
    - value: "github-dark-dimmed"
      label: "GitHub Dark Dimmed"
    - value: "github-dark-high-contrast"
      label: "GitHub Dark High Contrast"
    - value: "github-light"
      label: "GitHub Light"
    - value: "github-light-default"
      label: "GitHub Light Default"
    - value: "github-light-high-contrast"
      label: "GitHub Light High Contrast"
    - value: "houston"
      label: "Houston"
    - value: "laserwave"
      label: "LaserWave"
    - value: "light-plus"
      label: "Light Plus"
    - value: "material-theme"
      label: "Material Theme"
    - value: "material-theme-darker"
      label: "Material Theme Darker"
    - value: "material-theme-lighter"
      label: "Material Theme Lighter"
    - value: "material-theme-ocean"
      label: "Material Theme Ocean"
    - value: "material-theme-palenight"
      label: "Material Theme Palenight"
    - value: "min-dark"
      label: "Min Dark"
    - value: "min-light"
      label: "Min Light"
    - value: "monokai"
      label: "Monokai"
    - value: "night-owl"
      label: "Night Owl"
    - value: "nord"
      label: "Nord"
    - value: "one-dark-pro"
      label: "One Dark Pro"
    - value: "one-light"
      label: "One Light"
    - value: "plastic"
      label: "Plastic"
    - value: "poimandres"
      label: "Poimandres"
    - value: "red"
      label: "Red"
    - value: "rose-pine"
      label: "Rosé Pine"
    - value: "rose-pine-dawn"
      label: "Rosé Pine Dawn"
    - value: "rose-pine-moon"
      label: "Rosé Pine Moon"
    - value: "slack-dark"
      label: "Slack Dark"
    - value: "slack-ochin"
      label: "Slack Ochin"
    - value: "snazzy-light"
      label: "Snazzy Light"
    - value: "solarized-dark"
      label: "Solarized Dark"
    - value: "solarized-light"
      label: "Solarized Light"
    - value: "synthwave-84"
      label: "Synthwave '84"
    - value: "tokyo-night"
      label: "Tokyo Night"
    - value: "vesper"
      label: "Vesper"
    - value: "vitesse-black"
      label: "Vitesse Black"
    - value: "vitesse-dark"
      label: "Vitesse Dark"
    - value: "vitesse-light"
      label: "Vitesse Light"

apiVersion: v1alpha1
kind: Setting
metadata:
  name: shiki-settings
spec:
  forms:
    - group: config
      label: 配置  
      formSchema:
        - $formkit: select
          name: themeLight
          label: 亮色主题
          value: "vitesse-light"
          <<: *theme-options
        - $formkit: select
          name: themeDark
          label: 暗色主题
          value: "vitesse-dark"
          <<: *theme-options
        - $formkit: checkbox
          name: useBuiltinStyle
          label: 使用内置样式
          value: true
          help: 开启后将注入插件内置的代码块 css，关闭后将只使用主题提供的 css。
            