theme-options: &theme-options
  options:
    - value: "andromeeda"
      label: "andromeeda"
    - value: "aurora-x"
      label: "aurora-x"
    - value: "ayu-dark"
      label: "ayu-dark"
    - value: "catppuccin-frappe"
      label: "catppuccin-frappe"
    - value: "catppuccin-latte"
      label: "catppuccin-latte"
    - value: "catppuccin-macchiato"
      label: "catppuccin-macchiato"
    - value: "catppuccin-mocha"
      label: "catppuccin-mocha"
    - value: "dark-plus"
      label: "dark-plus"
    - value: "dracula"
      label: "dracula"
    - value: "dracula-soft"
      label: "dracula-soft"
    - value: "everforest-dark"
      label: "everforest-dark"
    - value: "everforest-light"
      label: "everforest-light"
    - value: "github-dark"
      label: "github-dark"
    - value: "github-dark-default"
      label: "github-dark-default"
    - value: "github-dark-dimmed"
      label: "github-dark-dimmed"
    - value: "github-dark-high-contrast"
      label: "github-dark-high-contrast"
    - value: "github-light"
      label: "github-light"
    - value: "github-light-default"
      label: "github-light-default"
    - value: "github-light-high-contrast"
      label: "github-light-high-contrast"
    - value: "houston"
      label: "houston"
    - value: "kanagawa-dragon"
      label: "kanagawa-dragon"
    - value: "kanagawa-lotus"
      label: "kanagawa-lotus"
    - value: "kanagawa-wave"
      label: "kanagawa-wave"
    - value: "laserwave"
      label: "laserwave"
    - value: "light-plus"
      label: "light-plus"
    - value: "material-theme"
      label: "material-theme"
    - value: "material-theme-darker"
      label: "material-theme-darker"
    - value: "material-theme-lighter"
      label: "material-theme-lighter"
    - value: "material-theme-ocean"
      label: "material-theme-ocean"
    - value: "material-theme-palenight"
      label: "material-theme-palenight"
    - value: "min-dark"
      label: "min-dark"
    - value: "min-light"
      label: "min-light"
    - value: "monokai"
      label: "monokai"
    - value: "night-owl"
      label: "night-owl"
    - value: "nord"
      label: "nord"
    - value: "one-dark-pro"
      label: "one-dark-pro"
    - value: "one-light"
      label: "one-light"
    - value: "plastic"
      label: "plastic"
    - value: "poimandres"
      label: "poimandres"
    - value: "red"
      label: "red"
    - value: "rose-pine"
      label: "rose-pine"
    - value: "rose-pine-dawn"
      label: "rose-pine-dawn"
    - value: "rose-pine-moon"
      label: "rose-pine-moon"
    - value: "slack-dark"
      label: "slack-dark"
    - value: "slack-ochin"
      label: "slack-ochin"
    - value: "snazzy-light"
      label: "snazzy-light"
    - value: "solarized-dark"
      label: "solarized-dark"
    - value: "solarized-light"
      label: "solarized-light"
    - value: "synthwave-84"
      label: "synthwave-84"
    - value: "tokyo-night"
      label: "tokyo-night"
    - value: "vesper"
      label: "vesper"
    - value: "vitesse-black"
      label: "vitesse-black"
    - value: "vitesse-dark"
      label: "vitesse-dark"
    - value: "vitesse-light"
      label: "vitesse-light"

apiVersion: v1alpha1
kind: Setting
metadata:
  name: shiki-settings
spec:
  forms:
    - group: config
      label: 配置  
      formSchema:
        - $formkit: select
          name: themeLight
          label: 亮色主题
          value: "vitesse-light"
          <<: *theme-options
        - $formkit: select
          name: themeDark
          label: 暗色主题
          value: "vitesse-dark"
          <<: *theme-options
            